### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by JohnCIT** [comment]
No problem. Use what ever you want on here :)

**Comment by jpbida** [comment]
Thanks!

**Comment by JohnCIT** [comment]
If I remember correctly there was some stuff in there that does not need to be. Like the loading bar, that was to only to fulfill some silly requirements in an assignment. Feel free to take it out or take bits of it. I really don't mind what is done with it at all :)

If you don't mind could I see it on your site at some point? It would be nice to see it get used for something.

**Comment by jpbida** [comment]
Thanks! I am running and after school program and want a bunch of games
kids can play and modify. It's nice to have a variety of starting points.
I'll send another pull request to add a link to where your game is hosted
on our public site if we use it.

**Pull request merged**
